services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: on-failure
    depends_on:
      - mariadb

  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: on-failure
    depends_on:
      - wordpress

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/brivera42/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/brivera42/data/wordpress

networks:
  inception:
    driver: bridge
