services:
  mariadb:
    build: ../srcs/requirements/mariadb
    container_name: mariadb
    env_file: .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

  wordpress:
    build: requirements_bonus/wordpress
    container_name: wordpress
    env_file: .env
    secrets:
      - db_password
      - wp_admin_password
      - wpuser_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: on-failure
    depends_on:
      mariadb:
        condition: service_started
      redis:
        condition: service_healthy

  nginx:
    build: ../srcs/requirements/nginx
    container_name: nginx
    env_file: .env
    ports:
      - "${HTTPS_PORT:-443}:443"
    secrets:
      - server.crt
      - server.key
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: on-failure
    depends_on:
      - wordpress

  redis:
    build: requirements_bonus/redis
    container_name: redis
    ports:
      - "6379:6379"
    secrets:
      - redis_password
    volumes:
      - redis_data:/data
    networks:
      - inception
    restart: on-failure
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
  ftp:
    build: requirements_bonus/ftp
    container_name: ftp
    secrets:
      - ftp_password
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress_data:/home/ftpuser/wordpress 
    networks:
      - inception
    restart: on-failure
    depends_on:
      - wordpress

  static:
    build: requirements_bonus/static
    container_name: static
    networks:
      - inception
    restart: on-failure
    ports:
      - "80:80"

secrets:
  db_password:
    file: ../secrets/db_password
  db_root_password:
    file: ../secrets/db_root_password
  wp_admin_password:
    file: ../secrets/wp_admin_password
  wpuser_password:
    file: ../secrets/wpuser_password
  redis_password:
    file: ../secrets/redis_password
  server.crt:
    file: ../secrets/server.crt
  server.key:
    file: ../secrets/server.key
  ftp_password:
    file: ../secrets/ftp_password 

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/redis

networks:
  inception:
    driver: bridge
